apiVersion: apps/v1
kind: Deployment
metadata:
  name: aicbc-beat
spec:
  template:
    spec:
      containers:
        - name: beat
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
