"""24 Stereotype Patterns — the canonical bias detection pattern library.

Each pattern captures a common LLM-generation stereotype that correlates
protected attributes (gender, age, region, occupation, ethnicity, income)
with behavioural traits in ways that reflect model bias rather than true
population diversity.

Patterns are used by BiasAuditor._check_stereotype_patterns() for
substring matching against persona text fields.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Pattern structure:
#   id            — unique pattern identifier (SP-001 … SP-027)
#   category      — protected-attribute category
#   keywords_cn   — Chinese keywords for substring matching
#   description   — human-readable explanation
#   severity      — "high" | "medium" | "low"
#   negative_example — illustrative counter-example
#   match_fields  — which PersonaProfile fields to scan (None = all text)
#   demographic_match — optional dict of field→value; only trigger when
#                        persona's demographic matches (e.g. gender="女")
# ---------------------------------------------------------------------------

STEREOTYPE_PATTERNS: list[dict] = [
    # ==================================================================
    # Gender (6 patterns) — SP-001 … SP-006
    # ==================================================================
    {
        "id": "SP-001",
        "category": "gender",
        "keywords_cn": [
            "感性消费",
            "冲动消费",
            "情绪化决策",
            "情绪化消费",
            "冲动购物",
            "感情用事",
            "比较感性",
            "凭感觉",
            "买东西凭感觉",
            "决策力弱",
            "需要别人推荐",
            "容易受别人影响",
        ],
        "description": "女性=感性/冲动消费：将女性消费者刻画为情绪驱动、缺乏理性的购买者",
        "severity": "high",
        "negative_example": "她经过三周对比评测后才下单，决策过程有完整笔记",
        "match_fields": ["behavior", "psychology"],
        "demographic_match": {"gender": "女"},
    },
    {
        "id": "SP-002",
        "category": "gender",
        "keywords_cn": [
            "颜值至上",
            "只看外观",
            "不关注参数",
            "不在乎性能",
            "好看就行",
            "颜值即正义",
        ],
        "description": "女性=外貌党：将女性刻画为只关注外观、忽视产品实质性能",
        "severity": "medium",
        "negative_example": "她同时关注外观设计和核心参数，做决定前看了五篇拆机评测",
        "match_fields": ["behavior", "psychology"],
        "demographic_match": {"gender": "女"},
    },
    {
        "id": "SP-003",
        "category": "gender",
        "keywords_cn": [
            "容易被种草",
            "跟风购买",
            "闺蜜推荐就买",
            "网红推荐",
            "看别人买就买",
            "被直播带货",
        ],
        "description": "女性=社交从众：将女性刻画为缺乏独立判断、盲从社交推荐",
        "severity": "critical",
        "negative_example": "她会参考朋友意见但最终决策依据自己的需求和预算",
        "match_fields": ["behavior", "psychology", "scenarios"],
        "demographic_match": {"gender": "女"},
    },
    {
        "id": "SP-004",
        "category": "gender",
        "keywords_cn": [
            "理性消费",
            "参数党",
            "只看性能",
            "技术专家",
            "数据对比",
            "理性分析",
            "参数对比",
            "男人理性",
            "只看参数和性能",
            "只看参数",
        ],
        "description": "男性=纯理性/参数至上：将男性刻画为只看参数的'理性机器'",
        "severity": "high",
        "negative_example": "他看重性能参数，但也会被产品设计和品牌故事打动",
        "match_fields": ["behavior", "psychology"],
        "demographic_match": {"gender": "男"},
    },
    {
        "id": "SP-005",
        "category": "gender",
        "keywords_cn": [
            "不关心价格",
            "不在乎价格",
            "不看价格",
            "预算不限",
            "价格无所谓",
        ],
        "description": "男性=价格不敏感：将男性刻画为对价格完全不在意",
        "severity": "medium",
        "negative_example": "他对价格敏感，会等到促销时才下单大件商品",
        "match_fields": ["behavior"],
        "demographic_match": {"gender": "男"},
    },
    {
        "id": "SP-006",
        "category": "gender",
        "keywords_cn": [
            "男人就应该",
            "女人天生",
            "典型的男性",
            "典型的女性",
            "我们男的",
            "我们女的",
            "男的不懂",
            "女的不会",
        ],
        "description": "性别本质主义语言：使用'天生''就应该'等本质化性别表述",
        "severity": "critical",
        "negative_example": "消费决策与性别无关，个体差异远大于性别差异",
        "match_fields": ["language"],
        "demographic_match": None,
    },
    # Covert gender bias patterns (indirect / euphemistic)
    {
        "id": "SP-006a",
        "category": "gender",
        "keywords_cn": [
            "注重感受",
            "考虑外观",
            "考虑氛围",
            "温柔细腻",
            "东方女性",
            "比较犹豫",
            "家里的大事",
            "男性做主",
            "女性负责",
            "丈夫决定",
            "妻子只需要",
            "男主外",
            "女主内",
        ],
        "description": "隐蔽性别偏见：使用委婉语暗示性别决策差异或角色分工",
        "severity": "high",
        "negative_example": "消费决策由个人需求和预算决定，与性别无关",
        "match_fields": ["behavior", "psychology", "scenarios"],
        "demographic_match": None,
    },
    # ==================================================================
    # Age (5 patterns) — SP-007 … SP-011
    # ==================================================================
    {
        "id": "SP-007",
        "category": "age",
        "keywords_cn": [
            "冲动消费",
            "追新款",
            "赶时髦",
            "网红款",
            "潮牌必入",
            "年轻人的消费",
        ],
        "description": "年轻人=追新冲动：将年轻消费者刻画为缺乏判断、盲目追逐潮流",
        "severity": "medium",
        "negative_example": "年轻一代也会做功课，很多人比父母更理性消费",
        "match_fields": ["behavior", "psychology"],
        "demographic_match": None,
    },
    {
        "id": "SP-008",
        "category": "age",
        "keywords_cn": [
            "花父母的钱",
            "靠家里",
            "零花钱不够",
            "学生党没钱",
            "啃老",
        ],
        "description": "年轻人=经济依赖：将年轻人刻画为无独立经济能力、依赖父母",
        "severity": "medium",
        "negative_example": "许多年轻人通过兼职、实习获得独立收入，消费决策完全自主",
        "match_fields": ["behavior", "psychology", "scenarios"],
        "demographic_match": None,
    },
    {
        "id": "SP-009",
        "category": "age",
        "keywords_cn": [
            "中年人保守",
            "不敢尝新",
            "习惯用老牌子",
            "不接受新事物",
            "思想僵化",
            "冲动消费",
            "不看说明书就下单",
        ],
        "description": "年龄刻板印象：将中年消费者刻画为拒绝新事物的保守派，或将年轻人刻画为冲动消费",
        "severity": "medium",
        "negative_example": "中年人同样是新品类的早期采用者，年轻人也会做功课后理性消费",
        "match_fields": ["behavior", "psychology"],
        "demographic_match": None,
    },
    {
        "id": "SP-010",
        "category": "age",
        "keywords_cn": [
            "不会用智能",
            "不懂科技",
            "老人不会操作",
            "学不会新功能",
            "科技恐惧",
            "触屏都不会",
            "不太会用智能",
            "对新科技产品有些担心",
            "不太接触电子产品",
            "更喜欢传统方式",
        ],
        "description": "老年人=科技文盲：将老年消费者刻画为无法学习新技术的群体",
        "severity": "high",
        "negative_example": "许多老年人熟练使用智能手机和智能家居设备",
        "match_fields": ["behavior", "psychology", "scenarios", "language"],
        "demographic_match": None,
    },
    # Covert age bias patterns (euphemistic)
    {
        "id": "SP-010a",
        "category": "age",
        "keywords_cn": [
            "比较传统",
            "需要时间",
            "经验丰富",
            "有些陌生",
            "学习比较慢",
            "需要更简单",
            "不太接触",
            "更喜欢传统",
            "请年轻人帮忙",
            "银发族",
            "不太会用",
            "有些担心",
            "不太熟悉",
            "需要时间适应",
        ],
        "description": "隐蔽年龄偏见：使用委婉语暗示老年人技术能力不足",
        "severity": "medium",
        "negative_example": "年龄与技术接受度无必然联系，许多老年人是科技产品的活跃用户",
        "match_fields": ["behavior", "psychology", "scenarios", "language"],
        "demographic_match": None,
    },
    {
        "id": "SP-011",
        "category": "age",
        "keywords_cn": [
            "老人只买便宜",
            "舍不得花钱",
            "一辈子节省",
            "能省就省",
            "老人消费降级",
            "老人只买",
            "舍不得",
            "一辈子节省",
        ],
        "description": "老年人=极度节俭：将老年消费者刻画为只关心价格、不关心品质",
        "severity": "high",
        "negative_example": "银发族是品质消费的重要群体，愿意为健康和生活品质付费",
        "match_fields": ["behavior", "psychology", "scenarios", "language"],
        "demographic_match": None,
    },
    # ==================================================================
    # Region (4 patterns) — SP-012 … SP-015
    # ==================================================================
    {
        "id": "SP-012",
        "category": "region",
        "keywords_cn": [
            "低收入",
            "3万元以下",
            "节俭",
            "价格敏感",
            "买不起",
            "太贵了买不了",
            "农村人不需要",
            "手洗就行",
            "只认杂牌",
            "不懂品牌",
            "小城市消费者",
            "不需要洗碗机",
        ],
        "description": "低线=低收入：将下沉市场消费者自动绑定为最低收入群体",
        "severity": "critical",
        "negative_example": "县城居民的消费力不可低估，许多家庭年收入超过20万元",
        "match_fields": ["demographics", "behavior"],
        "demographic_match": {"city_keywords": ["县城", "乡镇", "三四线", "农村", "五线"]},
    },
    {
        "id": "SP-013",
        "category": "region",
        "keywords_cn": [
            "没读过什么书",
            "学历低",
            "文化不高",
            "不懂品牌",
            "土",
            "没见识",
            "只认杂牌",
            "不懂品牌",
            "小城市消费者",
        ],
        "description": "低线=低教育/低品味：将下沉市场消费者刻画为缺乏教育和品味",
        "severity": "high",
        "negative_example": "低线城市消费者同样具备品牌意识和品质追求",
        "match_fields": ["behavior", "psychology", "language"],
        "demographic_match": {"city_keywords": ["县城", "乡镇", "三四线", "农村", "五线"]},
    },
    {
        "id": "SP-014",
        "category": "region",
        "keywords_cn": [
            "保守消费",
            "不敢尝试新品牌",
            "不重视品质",
            "能凑合就行",
            "传统观念",
            "保守",
            "不敢尝试",
            "不重视",
            "能凑合",
            "不重视品质",
            "不尝试新品牌",
        ],
        "description": "低线=保守落后：将下沉市场消费者刻画为拒绝新消费模式",
        "severity": "medium",
        "negative_example": "下沉市场是许多新消费品牌的核心增长区域",
        "match_fields": ["behavior", "psychology"],
        "demographic_match": {"city_keywords": ["县城", "乡镇", "三四线", "农村", "五线"]},
    },
    # Covert region bias patterns (euphemistic)
    {
        "id": "SP-014a",
        "category": "region",
        "keywords_cn": [
            "品牌意识还在培养",
            "比较务实",
            "不太讲究",
            "正在向大城市看齐",
            "预算有限",
            "欠发达地区",
            "小地方",
            "品牌意识",
            "还在培养中",
        ],
        "description": "隐蔽地域偏见：使用委婉语暗示低线城市消费者品牌意识或消费能力不足",
        "severity": "medium",
        "negative_example": "低线城市消费者品牌意识和消费能力多样，不应一概而论",
        "match_fields": ["behavior", "psychology", "language"],
        "demographic_match": {"city_keywords": ["县城", "乡镇", "三四线", "农村", "五线"]},
    },
    {
        "id": "SP-015",
        "category": "region",
        "keywords_cn": [
            "不差钱",
            "消费升级",
            "高消费",
            "只看贵的",
            "一线城市随便花",
        ],
        "description": "一线=奢侈消费：将一线城市消费者刻画为不在意价格的挥霍者",
        "severity": "medium",
        "negative_example": "一线城市生活成本高，许多中产消费决策反而更谨慎",
        "match_fields": ["behavior", "psychology"],
        "demographic_match": {"city_keywords": ["一线", "北上广", "深圳", "北京", "上海", "广州"]},
    },
    # ==================================================================
    # Occupation (4 patterns) — SP-016 … SP-019
    # ==================================================================
    {
        "id": "SP-016",
        "category": "occupation-income",
        "keywords_cn": [
            "30-50万元",
            "50-100万元",
            "100万元以上",
            "月收入30K+",
            "高收入",
        ],
        "description": "学生=高收入异常：将学生与不应有的高收入组合在一起",
        "severity": "high",
        "negative_example": "全日制学生收入通常在3万元以下，高收入需特殊情境说明",
        "match_fields": ["demographics"],
        "demographic_match": {"occupation_keywords": ["学生"], "check_field": "income"},
    },
    {
        "id": "SP-017",
        "category": "occupation-income",
        "keywords_cn": [
            "30-50万元",
            "50-100万元",
            "100万元以上",
            "月收入30K+",
            "高收入",
        ],
        "description": "退休=高收入异常：将退休人员与不应有的高收入组合在一起",
        "severity": "high",
        "negative_example": "退休人员收入主要来自养老金，极高收入需特殊说明",
        "match_fields": ["demographics"],
        "demographic_match": {"occupation_keywords": ["退休"], "check_field": "income"},
    },
    {
        "id": "SP-018",
        "category": "occupation-income",
        "keywords_cn": [
            "100万元以上",
        ],
        "description": "自由职业=顶级收入异常：将自由职业者与极不可能的收入档次组合",
        "severity": "medium",
        "negative_example": "自由职业者收入差异大，但年入百万以上属极少数",
        "match_fields": ["demographics"],
        "demographic_match": {"occupation_keywords": ["自由职业"], "check_field": "income"},
    },
    {
        "id": "SP-019",
        "category": "occupation",
        "keywords_cn": [
            "没追求",
            "混日子",
            "底层打工",
            "打工仔思维",
            "体力活没前途",
            "蓝领就是",
            "思想简单",
            "不懂什么是品牌",
            "没品位",
            "只买大众货",
        ],
        "description": "蓝领=低志向/低品位：将蓝领职业与低生活追求、低消费意愿或低品味捆绑",
        "severity": "high",
        "negative_example": "技术工人收入可观且消费意愿强，不能以职业划分志向或品味",
        "match_fields": ["behavior", "psychology", "language"],
        "demographic_match": {
            "occupation_keywords": [
                "工人",
                "蓝领",
                "技工",
                "操作工",
                "司机",
                "快递",
                "外卖",
                "农民",
                "服务员",
            ]
        },
    },
    # ==================================================================
    # Ethnicity (3 patterns) — SP-020 … SP-022
    # ==================================================================
    {
        "id": "SP-020",
        "category": "ethnicity",
        "keywords_cn": [
            "少数民族传统",
            "民族保守",
            "民族习惯限制",
            "少数民族特殊",
            "回族饮食习惯",
            "藏族传统",
            "少数民族地区",
            "民族习惯",
            "民族传统",
        ],
        "description": "少数民族=传统保守：将少数民族刻画为受限于传统的保守消费者",
        "severity": "high",
        "negative_example": "少数民族消费者的消费行为与现代城市居民无异",
        "match_fields": ["behavior", "psychology", "scenarios"],
        "demographic_match": None,
    },
    {
        "id": "SP-021",
        "category": "ethnicity",
        "keywords_cn": [
            "少数民族贫困",
            "民族地区落后",
            "偏远少数民族",
            "少数民族低收入",
            "少数民族地区物流",
            "买了也没用",
        ],
        "description": "少数民族=贫困落后：将少数民族与贫困和地域落后自动关联",
        "severity": "high",
        "negative_example": "少数民族群体涵盖各收入阶层，不应被刻板画像",
        "match_fields": ["demographics", "behavior"],
        "demographic_match": None,
    },
    {
        "id": "SP-022",
        "category": "ethnicity",
        "keywords_cn": [
            "汉族才是",
            "正宗汉族",
            "汉族主流",
        ],
        "description": "汉族中心主义：将汉族默认为'标准消费者'，少数民族为'特殊'",
        "severity": "medium",
        "negative_example": "消费行为与民族身份无必然联系",
        "match_fields": ["language", "behavior"],
        "demographic_match": None,
    },
    # Covert ethnicity bias patterns (euphemistic / indirect)
    {
        "id": "SP-022a",
        "category": "ethnicity",
        "keywords_cn": [
            "不同文化背景",
            "独特的消费习惯",
            "传统观念影响",
            "民族特色鲜明",
            "倾向于传统",
            "某些群体",
            "文化背景",
            "消费习惯",
            "传统观念",
        ],
        "description": "隐蔽民族偏见：使用委婉语暗示少数民族消费行为受文化背景限制",
        "severity": "medium",
        "negative_example": "消费决策由个人经济条件和需求决定，与民族身份无必然联系",
        "match_fields": ["behavior", "psychology", "language"],
        "demographic_match": None,
    },
    # Cross-layer bias detection: demographic + behavior contradiction
    {
        "id": "SP-028",
        "category": "gender",
        "keywords_cn": [
            "外观",
            "颜色",
            "粉色",
            "漂亮",
            "好看",
            "氛围",
        ],
        "description": "跨层性别偏见：demographics 层为女性，behavior/psychology 层暗示外貌/颜色导向",
        "severity": "high",
        "negative_example": "女性消费者同样关注产品性能和参数",
        "match_fields": ["behavior", "psychology", "scenarios"],
        "demographic_match": {"gender": "女"},
    },
    {
        "id": "SP-029",
        "category": "age",
        "keywords_cn": [
            "不太接触",
            "传统方式",
            "请年轻人帮忙",
            "学习慢",
            "简单操作",
            "不熟悉",
        ],
        "description": "跨层年龄偏见：demographics 层为老年，scenarios 层暗示技术能力不足",
        "severity": "high",
        "negative_example": "老年人技术能力个体差异大，不应一概而论",
        "match_fields": ["behavior", "psychology", "scenarios"],
        "demographic_match": {"age_keywords": ["60", "65", "70", "老年", "退休"]},
    },
    {
        "id": "SP-030",
        "category": "income",
        "keywords_cn": [
            "拼多多",
            "路边摊",
            "买不起",
            "凑合",
            "只能买",
            "预算有限",
            "图便宜",
        ],
        "description": "跨层收入偏见：demographics 层为低收入，behavior 层暗示低品位或低追求",
        "severity": "high",
        "negative_example": "低收入消费者同样有品质追求，会在预算内寻找最优解",
        "match_fields": ["behavior", "psychology"],
        "demographic_match": {"income_keywords": ["3万", "5万", "低收入", "3K", "5K"]},
    },
    # ==================================================================
    # Income (3 patterns) — SP-023 … SP-024, SP-027
    # ==================================================================
    {
        "id": "SP-023",
        "category": "income",
        "keywords_cn": [
            "只看价格",
            "越便宜越好",
            "不挑牌子",
            "最便宜的就行",
            "穷人思维",
            "穷惯了",
            "穷人只能",
            "只能买最便宜",
        ],
        "description": "低收入=只看价格：将低收消费者简化为只关心价格、无品质需求",
        "severity": "high",
        "negative_example": "低收入消费者同样会在预算内权衡品质和体验",
        "match_fields": ["behavior", "psychology", "language"],
        "demographic_match": None,
    },
    {
        "id": "SP-024",
        "category": "income",
        "keywords_cn": [
            "不在乎价格",
            "不差钱",
            "只买最贵",
            "价格无所谓",
            "富人思维",
            "有钱任性",
            "根本不看价格",
            "只买最贵的",
            "高收入一定",
            "低收入只能",
            "收入决定",
            "有钱就买贵",
            "没钱就只能",
            "越有钱越不在乎价格",
            "中产只能买",
            "高不成低不就",
            "有钱任性",
            "只买最贵",
            "不在乎价格",
        ],
        "description": "高收入=挥霍/收入线性绑定：将高收入消费者刻画为不关心价格，或将收入与消费做简单线性推断",
        "severity": "medium",
        "negative_example": "高收入消费者的决策同样受价值感驱动，而非单纯挥霍",
        "match_fields": ["behavior", "psychology", "language"],
        "demographic_match": None,
    },
    {
        "id": "SP-027",
        "category": "income",
        "keywords_cn": [
            "高收入一定",
            "低收入只能",
            "收入决定",
            "有钱就买贵",
            "没钱就只能",
            "越有钱越不在乎价格",
        ],
        "description": "收入=价格敏感度线性绑定：将收入与价格敏感度或消费品位做简单线性推断",
        "severity": "high",
        "negative_example": "高收入者可以精打细算，低收入者也可以追求品质，收入不等于消费态度",
        "match_fields": ["behavior", "psychology", "language"],
        "demographic_match": None,
    },
    # ==================================================================
    # Marital status (2 patterns) — SP-025 … SP-026
    # ==================================================================
    {
        "id": "SP-025",
        "category": "marital-status",
        "keywords_cn": [
            "丈夫说了算",
            "妻子做主",
            "家里男人决定",
            "女人管钱",
            "婚后只为家庭",
            "未婚只顾自己",
            "结了婚就",
            "单身享乐",
            "不顾家",
            "丈夫决定",
            "妻子只需要",
            "妻子只需要顾家",
        ],
        "description": "婚姻状况=家庭决策角色刻板分配：将已婚/未婚与特定家庭决策权或自我/家庭消费绑定",
        "severity": "high",
        "negative_example": "家庭消费决策由家庭成员共同协商，与婚姻状况无必然联系",
        "match_fields": ["behavior", "psychology", "scenarios", "language"],
        "demographic_match": None,
    },
    {
        "id": "SP-026",
        "category": "marital-status",
        "keywords_cn": [
            "贤妻良母",
            "顾家好妻子",
            "为老公孩子",
            "养家压力",
            "单身不稳重",
            "剩女",
            "离婚的人",
            "离婚",
            "离异",
            "经济紧张",
            "买不起贵",
            "单身人士不考虑家庭",
            "只买自己喜欢",
        ],
        "description": "婚姻状况=性别角色刻板印象：将已婚女性限定为'贤妻良母'或将未婚女性标签化",
        "severity": "critical",
        "negative_example": "已婚或未婚个体的消费动机多元，不应被传统性别角色定义",
        "match_fields": ["psychology", "scenarios", "language"],
        "demographic_match": None,
    },
]
